name: mamba-stfm
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11.10
  - pytorch=2.4.1
  - pytorch-cuda=12.1
  - numpy=1.26.4
  - scipy=1.13.1
  - scikit-learn=1.5.2
  - pyyaml=6.0.2
  - pip=24.3.1
  - pip:
      - mne==1.8.0
      - moabb==1.1.1
